### ISSUE TITLE
Page generation

### ISSUE THREAD

**Issue by fritzk** [BabylonJS/Spector.js#113] opened 2019-08-26 22:47 UTC
Feature request:
Debugging WebGL is much simpler if there is a simple repro available.  It would be helpful if spector.js could generate a webpage with the data between draw calls.  It is helpful the way that spector.js shows the frames and the draw calls used, but there is no way to replay them.

**Comment by sebavan** [comment] 2019-08-26 23:24
I love the idea and I really wanted to do it at first.

Unfortunately this requires to record too much info to be fully consistent and is making the memory explode in a lot of cases. (the data are all stored to JSON at the moment and buffer are a huge part of the problem here) 

For instance, the buffer content is not tracked by design to not reach the memory limit as fast. Also it reinsures apps creator to know that Spector is not usable directly to "steal" assets data. This was one of the issue with buffer recording and the second main reason it was pulled out before the first release.

The 2 biggest questions would be :
- How would you see this working in JSON ?
- Would it be just a diff for the experience or more a standalone replay ?

**Comment by sebavan** [comment] 2019-08-27 22:47
By start of recording, you basically mean the full frame ? not from the start of the app ?

Yup the more I am thinking about it the harder it sounds without going through the full asset setup recording.

**Comment by sebavan** [comment] 2019-10-03 17:34
closing for now as it does not sound achievable

**Closed by sebavan** 2019-10-03 17:34 UTC
