### ISSUE TITLE
Feature request: WebGL scene export to glTF

### ISSUE THREAD

**Issue by cx20** [BabylonJS/Spector.js#49] opened 2017-07-26 21:13 UTC
I do not know if it is feasible, however I think it is useful to be able to export WebGL scene in glTF format.

The following is an image of the feature.
![image](https://user-images.githubusercontent.com/1833979/28643774-ecb3734a-7291-11e7-9c46-8072e1e0092a.png)

![image](https://user-images.githubusercontent.com/1833979/28643791-fbecaa8e-7291-11e7-8f61-84e5aa2d91ac.png)

**Comment by sebavan** [comment] 2017-07-26 21:19
This would be fun but I am really wondering how this could work knowing the shaders are fully customs as well as the state management. Also gltf does not by design support the configuration of all the low level aspects of webgl so it can be impossible to make a match in some certain cases.

**Comment by cx20** [comment] 2017-07-26 21:43
I thought that it was a good idea, but it sounds difficult...
If it is difficult to reproduce everything, it is useful to be able to export only vertex data and texture information.
For example, if you can export the vertex data, you can check the geometry with the viewer, or if you can export vertex data and texture, you can display and edit in Paint 3D.

**Comment by sebavan** [comment] 2017-08-01 06:48
I am afraid of such cases unfortunately as it could be to easily badly use :-)

I will close it for now and I opened a reminder for vNext that should start in September.

**Closed** 2017-08-01 06:48 UTC
