### ISSUE TITLE
Support RenderingContext.prototype.call

### ISSUE THREAD

**Issue by dakom** [BabylonJS/Spector.js#94] opened 2018-12-20 13:58 UTC
It seems that Spector, the browser extension at least, doesn't work with contexts created through wasm:

For example, try loading this page with the extension enabled, and the red button does not open the report:
https://rustwasm.github.io/wasm-bindgen/exbuild/webgl/

I also couldn't see a way to do this through the `spector` object on `window`

**Comment by sebavan** [comment] 2018-12-20 14:17
I ll look into it ASAP but are you also hooking on the context which could prevent the spector hook to work ?

I was thinking in the webgl.js file ?

Would be amazing if you have a bare webassembly/webgl example not evaled from webpack to see what we can do.

**Comment by sebavan** [comment] 2018-12-20 14:59
Ok so spector works fine, it is just that the samples does not render frames, just the first one shot render triangles :-)

You can then use the reload button to capture all the first 50 commands to understand every single calls :-)

![image](https://user-images.githubusercontent.com/16655165/50291863-fcc28c00-046f-11e9-8ff0-9dbfda40d456.png)

It takes a bit of time as there are only 20 commands called so it display the result after a timeout of 10 seconds.

Closing this issue but would be interested to see on bigger scale samples.

**Comment by dakom** [comment] 2018-12-21 08:10
I put together an independent demo: https://github.com/dakom/temp-webgl-wasm-test

The wasm+webgl part renders a quad, but I can't get Spector to work with it. Thinking maybe it's something with the Typescript wrangling or webpack bundling?

Note that the production build does minify via Terser, but the same issue happens locally without that (you can clone the repo, `npm install`, and `npm run dev` to see and test that).

Decided to keep the Rust/WASM build pipeline out of the repo since adding that in complicates things and I don't think there's anything really to change there (i.e. the JS loads the .wasm and doesn't need to know about what it does)

The only difference on the code side I see at a glance, in terms of the JS/WASM divide, is that in this demo I create the canvas element on the JS side and pass it to wasm, whereas in the official webgl reference above the canvas element is created on the wasm side too.

Any tips to get Spector working here are greatly appreciated! At a glance I think this means the issue might benefit from being re-opened until this is resolved, but there's a good chance I just missed something too ;)

Thanks!

**Comment by dakom** [comment] 2018-12-21 08:12
Oh I forgot to mention - the other difference is I'm using Typescript, so all the webpack bundling is going through that.

The `.tsx` extension is because in ideally I'd like to handle the UI on the JS side with React, though I didn't add that here for the sake of simplicity

**Comment by sebavan** [comment] 2018-12-21 13:22
So it looks like the issue is not wasm but the bindings.

It uses javascript call on the context making it impossible to hook per context. In spector, we hook at the context instance level not the context prototype itself to not pollute the default prototype.

Let me see if I could do smthg for it.

**Comment by dakom** [comment] 2018-12-21 14:03
Thanks for the insight and heads up! I'll be away today/tomorrow but back around on Sunday to try things out if it helps :)

**Comment by sebavan** [comment] 2019-01-07 10:45
I have began to look into the issue and modifying the prototype of the rendering is a huge architecture change. I am trying to find another approach if possible. It will nevertheless take a bit of time to develop :-) sorry for the delay.

**Comment by dakom** [comment] 2019-01-13 21:00
Whups, didn't realize it would lead to such a massive change! Sorry to be the bearer of bad news. Really appreciate your taking the time to work on this... but no pressure!

fwiw I'm still just getting the hang of basics in wasm/Rust (almost have a textured quad on the screen, hehe) - not really up to the proper shader stuff yet ;)

Spector is an _amazing_ tool and I can't imagine debugging without it :) I'm sure when the larger community catches on to wasm/webgl opportunities it'll be wonderful to have this fix ready and waiting :D

**Comment by sebavan** [comment] 2019-01-13 21:38
Yup totally agree and thanks for the nice feedback, just need to find a bit more time to sort it out but will probably require a local install not just from the extension from what I can see now.

**Comment by sebavan** [comment] 2019-02-15 17:54
It looks like hooking the entire context prototype is creating some issues. I am currently investigating a way to bypass some of the restrictions it created.

**Comment by edwinwalda** [comment] 2021-04-23 13:58
Hello! I am trying to debug a rust / WASM webgl build, and I inevitably ran into this issue. I just tested both the extension and npm build and neither seemed to work. What is the status of this refactor? If I fork this repo, is there a work around I could use to intercept the calls from WASM? Any bit of help or direction you could offer would be much appreciated! 

Also, thank you again for all your work on this, it's been a pleasure to use in many other projects.

**Comment by sebavan** [comment] 2021-04-23 21:13
Unfortunately no easy way to bypass those issues :-( you could try to change the way we do https://github.com/BabylonJS/Spector.js/blob/master/src/backend/spies/commandSpy.ts#L102 

Basically the way we execute the original command from the context. Totally open for any PRs here.

**Comment by edwinwalda** [comment] 2021-04-27 15:31
Thank you so much for the info! Fortunately we were able to resolve the problem, (a NaN snuck into our simulation) but in general we are very interested in using `spector` to help us with our project. So we'll take a look at this and see what we can do.

**Comment by sebavan** [comment] 2022-01-18 02:31
Closing for now, feel free to reopen if you make a PR

**Closed by sebavan** 2022-01-18 02:31 UTC
