### ISSUE TITLE
Crashing on models with 8k textures with full capture on

### ISSUE THREAD

**Issue by jxnkarl** [BabylonJS/Spector.js#241] opened 2022-08-30 08:40 UTC
It just makes chrome (I also tried different browsers) unresponsive and then after a couple of seconds later it just doesn't do anything. Otherwise it just crashes the tab

**Comment by RaananW** [comment] 2022-08-30 13:01
As written in the template you have used to create this issue, we discuss issues on the forum first. We keep github issues to verified bugs and features. 
You are more than welcomed to write us in the forum, and we promise to address your issue. A side note - a reproduction of your issue will be great, otherwise we can't really help.

**Comment by RaananW** [comment] 2022-08-30 13:02
Sorry, that was a mistake (didn't mean to close it). I'll leave this for @sebavan :-)

**Comment by sebavan** [comment] 2022-08-30 16:20
Yup it is unfortunately a know limitation of Spector as this blows up the memory. This is also why we do not capture at full size by default.

I will close as won t fix but happily accept PRs that would circumvent the issue.

**Closed by sebavan** 2022-08-30 16:20 UTC

**Comment by JannikGM** [comment] 2022-08-31 08:51
Just for completeness: What is the bottleneck?

- Capturing? (= tiling necessary to avoid large framebuffer)
- Storage? (= compression necessary)

Also, is there deduplication of data (likely by hashing) somewhere?

Wouldn't it be enough to plug some (lossless) compressor around the Spector data; likely by wrapping:

https://github.com/BabylonJS/Spector.js/blob/4941ba3633a4b5ece6983e7649342006ea7c7f73/src/backend/states/drawCalls/drawCallTextureInputState.ts#L144

..and potentially keeping everything in some (likely custom) hashmap for the deduplication?

**Comment by JannikGM** [comment] 2022-08-31 09:10
According to [this chrome patch](https://chromium.googlesource.com/chromium/src.git/+/dd15c29bcac43daf9271fbb60bd5a93607e39fe5/third_party/WebKit/Source/platform/image-encoders/skia/WEBPImageEncoder.cpp) via https://bugs.chromium.org/p/chromium/issues/detail?id=523098#c21, `toDataUrl` with webp encoder at 100% quality should produce a lossless webp, which should be a small change in the code, for potentially better compression (than the default png).

**Comment by JannikGM** [comment] 2022-08-31 09:32
Also, the data URL from `toDataURL()` will be huge because it's base64; not sure how the capture is stored in the end (JSON? that'd be bad..), but using some JS base64 decoder to somehow get a `Uint8Array` for storage would be nice).

Long term, if the code was made to handle async, we'd likely be able to use `.toBlob()` get an `ArrayBuffer` from the resulting `blob` which I'd expect to be faster.

**Comment by JannikGM** [comment] 2022-08-31 21:42
>  The only way around is a full rearchitecture

I did look at the code earlier, and I think it should be possible to at least hash the VisualState `src`, so reused textures don't get stored every time. I think it would make sense to introduce an `__SPECTOR_Resource_TAG` which replaces the `data:`-URL in `src`, where the capture has a `resources` array with the resource tags being an index into the resources.

> a kind of zip container to still ensure a single file sharing

How about BSON with `Uint8Array`?

> webp would have issues in some browsers when used from the npm package unfortunately

Is this really an issue? Couldn't WebP be the default, with a fallback option to use `png`, maybe even a dropdown for different quality settings / formats (similar to the full-capture checkbox)?

I don't think many people are sending JSON captures around to where WebP encoder and decoder (or lack thereof) would cause issues?
There are also WebP encoders / decoders written in JS.

One thing one might have to check for is wether WebP might do alpha premultiplication.

> and anyway is not scalable

What do you mean by that?

**Comment by sebavan** [comment] 2022-08-31 22:42
> What do you mean by that?

As long as it is all embedded in one really large file + fully in memory, there will be a limit to what we can hold :-) 

> How about BSON with `Uint8Array`?

Sounds like smthg to try out :-)

> I did look at the code earlier, and I think there's room for improvement with the current solution.

Yup "dedup-ing" is smthg we thought of earlier, and this is probably the biggest impact on size and such. It still requires quite some rework to ensure textures are not "dirty" alongside a capture but decoupling a versionned visual state from the usage point would be great.
